### ISSUE TITLE
For the sake of science...

### ISSUE THREAD

**Issue by PJVol** [irusanov/ZenStates-Core#12]
Hi! Just took a look into your acpimmio module, and wanted to ask
How did you know the bitmask for the cg1pll_fcw0_frac_override (CG1PLL_FBDIV_Fraction in old docs) ? )
In the docs I have it's either missing or incorrect.

**Comment by irusanov** [comment]
Asus tool that could set bclk, r/w everything to observe changes and some trial and error. It doesn't work correctly on Raphael though.

**Comment by PJVol** [comment]
Nice, and yeah, Asrock has the utility "A-Tuning", allowing to set bclk on-the-fly.
I was curious though, since my board has no external CG, if you're still able to control PLL fcw0 in this case... Is it just work as the clock reciever this way? 


> IIRC adjusted those masks 2-3 times before I got it correctly

You mean you have to do that constantly or it's about finding out the correct mask for Zen4?

**Comment by irusanov** [comment]
It was mostly intended for the internal PLL on boards without external one and the mobile machines, although the range is very limited. I'm not sure it will work in every case, perhaps it depeds how the board is configured (in the case when using external CG). For example, my current board (X670E Gene) has sync and async mode. In async mode it probably uses 2 different CG registers, but I haven't really looked into it yet.

My bad about Raphael, it is not working correctly on the 6800HS I have. It still sets it, but the masks (and/or fraction multiplicator) are probably different as the set BCLK is different than the intended one and the one that is calculated/read back.

**Comment by PJVol** [comment]
> My bad about Raphael, it is not working correctly on the 6800HS I have. It still sets it, but the masks (and/or fraction multiplicator) are probably different as the set BCLK is different than the intended one and the one that is calculated/read back.

I see... you meant Zen3+ not Zen4. 
Well, apparently APU in this regard is still a thing-in-itself

**Comment by irusanov** [comment]
You can try the ACPI BIOS function if there's one exposed. The SMU command for setting VSOC VID on the fly was blocked/removed a long time ago, unfortunately. You would need to restart and hopefully that setting sticks, even when hidden from the setup menu.

![image](https://github.com/irusanov/ZenStates-Core/assets/7671877/ad7b429b-eb36-4592-aecc-545e327e8b4e)

**Comment by PJVol** [comment]
I've tried ACPI commands from a console (no luck). Nice to see you have updated SDT )
I'll give it a try.

**Comment by PJVol** [comment]
Don't know why it didn't work from console, but it does work from your tool. Some thoughts:
1. There's ambiguous reference to "Formatting" in SettingsForm.cs (line 616) - solved it with 
Formatting = Newtonsoft.Json.Formatting.Indented
2. I had to remove and add again Assembly reference to Newtonsoft.Json to successfully build.

The only thing's left is to figure out how to set LL slope and Offset trims. They are encoded by 22:24 and 25:26 bits respectively.

**Comment by irusanov** [comment]
Doesn't cause issues for me, the package is included at the top and the enum is correctly referenced. Not that what you did is wrong though, but there must be some difference between mine and yours environments.
Also it is 815 line for me.

![image](https://github.com/irusanov/ZenStates-Core/assets/7671877/444978f2-9b0b-40ad-94ab-21ca3d89d187)

**Comment by PJVol** [comment]
Thanks!

**Comment by irusanov** [comment]
I have just tried with a 240GE running on B550 Unify-X and the vsoc didn't change, it seems to be using an auto-rule and all oveclocking features are not availvable in bios - voltages, P-States, VSOC VID, etc.

**Comment by PJVol** [comment]
> I have just tried with a 240GE running on B550 Unify-X and the vsoc didn't change, it seems to be using an auto-rule and all oveclocking features are not availvable in bios - voltages, P-States, VSOC VID, etc.

Are you entered Vsoc as SVI2 VID?
Anyway, what I talked initially is the way to control VRM directly, as the Asrock and other vendor's utilities do, changing controller settings runtime, i.e. without need to reboot. I believe they using SMBUS or I2C driver call to access PWM controller registers, because it seems the only way to set real voltages and offsets, PWM frequency, etc.
The load-line settings though exposed in BIOS seem to be accessible via SVI2, at least there are corresponding bitfields in a SMU::SMUIO::SMUSVI0_PLANE0_LOAD and SMU::SMUIO::SMUSVI0_PLANE1_LOAD registers mapped to the SMN address space.
The problem is these fields are readonly for IPs with trust level > 2, i.e. anything other than MP0, MP1, uCode, RSMU

**Comment by PJVol** [comment]
It's RAA 229004 (or ISL 69138) for the VDD_CPU and VDD_SOC
uP1674 for VDIMM
NCT3933U for VTT_DDR and 1P8V
There is a file 69138_test.xml in configs folder
