### ISSUE TITLE
Command line access or apply on startup possible?

### ISSUE THREAD

**Issue by fscottcopeland** [irusanov/ZenStates-Core#13]
Hey,

This app somehow appears to be the only way I've found that supports per-core CO on the laptop 7945HX. Is it possible to set CO on boot, or via a scheduled task, using this tool? If not, is this something which might be possible or do you have any recommendations?

Cheers!

**Comment by irusanov** [comment]
Hi,
It's not possible at its current state, the functionality needs to be implemented.

I don't have a 7x4x-based laptop, but if the Apply button works (I believe you're referring the SMU Debug Tool) and the value sticks, then it is good news. I haven't found a way to set CO values on my 6800HS.

I can quickly add load and save buttons on the PBO tab, so you can save the whole CO configuration per core and load it afterwards, but it would require a manual load and apply each time windows is loaded. It is also possible to add a command line support so it loads the config and applies it automatically - this would require more changes in the app. let me see what I can do.

Some of the values that are controllable runtime can be saved to bios and will be loaded on next boot, but it is rather risky on laptops without an easy way to clear cmos. I had to reflash mine with a clean bios and solder several wires to use by an external eeprom programmer. This is the reason I don't want to add the functionality to send the values to bios as they are saved in the hidden AMD CBS/OC menus and are hard to reset if something goes wrong and the laptops gets bricked.

**Comment by irusanov** [comment]
@fscottcopeland Here's a very rough version with support for saving, loading and automatically applying the saved CO values.
You need to adjust the values first on ```PBO``` tab, then click on ```Save```. The saved values are in a file located in ```profiles``` directory. ```Load``` button loads the file into the fields.

The app also supports a command line argument ```--applyprofile``` which will apply the profile on each app start. Additionally, there's a checkbox ```Apply saved profile on startup``` that when checked creates a scheduled task on user logon and when unchecked deletes it.

[SMUDebugTool_v1.35_20231213.zip](https://github.com/irusanov/ZenStates-Core/files/13665797/SMUDebugTool_v1.35_20231213.zip)

**Comment by fscottcopeland** [comment]
Hey @irusanov thanks for the reply!
This is fantastic. Seems to all work as intended for me, regarding the scheduled task. One thing to note is that it appears the user-set profile seems to get set in the local profiles folder, but the task scheduler profiles get set and loaded in system32.

This is really helpful. I suppose the only other thing will be full command line access, or a way for the profile to be set in the background without the app visibly opening. But, what you have done in under a day is absplutely fantastic, thank you again! Look forward to further updates to the main ZenStates soon :)

**Comment by irusanov** [comment]
> One thing to note is that it appears the user-set profile seems to get set in the local profiles folder, but the task scheduler profiles get set and loaded in system32.

Is that a problem? I'm not very experienced with the scheduled tasks in Windows. I wanted it to run for the local user saving the setting, but only after log in. This seemed to require the least privileges.

The functionality is pretty much hardcoded, it also relies on the UI loading. Applying it with a silent app load would require much more changes. I could add an automatic close, but decided it is not absolutely needed at the moment and leaving the app opened at the PBO tab would actually give a visual confirmation that the values are applied. I could add a notification as a confirmation of the successful operation.

This app, as it is, is really messy and not easy to maintain or extend. It was an internal testing tool aimed to help me debug, so I didn't even plan to add so many functions.

**Comment by fscottcopeland** [comment]
Sorry for the delay. Nope, not a problem at all, for me at least. An auto close or an apply in background would be nice though. CO settings seem to get reset upon sleep etc, but that can be somewhat mitigated by adding additional triggers to the scheduled task (which I have done).
