### ISSUE TITLE
Wrong MP1 ARG address here for Cezanne, Renoir etc.

### ISSUE THREAD

**Issue by PJVol** [irusanov/ZenStates-Core#4]
Hi!
https://github.com/irusanov/ZenStates-Core/blob/04d86d083748e24bcd8b9da3dfcdada36aebf0f0/SMU.cs#L347
347       Mp1Smu.SMU_ADDR_ARG = 0x03B10998;

**Comment by irusanov** [comment]
Hi,
I don't have a Cezanne or Renoir to check, but it makes sense it is the same as on older APUs. Will change it.

**Comment by irusanov** [comment]
Fixed in v1.6.2 of the DLL.
