### ISSUE TITLE
Question about GetPsmMarginSingleCore

### ISSUE THREAD

**Issue by tutyamxx** [irusanov/ZenStates-Core#8]
How do i specify the coreMask for core 5 for example to set a margin of -5?

I did try `cpu.SetPsmMarginSingleCore(5)` but it only applies for core 0. Sorry for creating this, due to lack of docs, i am confused.

**Comment by irusanov** [comment]
Hi,
Yeah, I know about the documentation, hopefully I will have more time for these projects soon.

There's a utility function exposed.
`cpu.MakeCoreMask(core, ccd, ccx);`

For Family 19h, you can omit ccx as it is always 0 and provide the ccd index and core index (in that ccd)
So, the get margin for core 5 (6th core) in ccd 0 (first ccd), you do

```
uint mask = cpu.MakeCoreMask(5, 0);
int? margin = cpu.GetPsmMarginSingleCore(mask);
```
To set -20 for core 5
```
uint mask = cpu.MakeCoreMask(5, 0);
cpu.SetPsmMarginSingleCore(mask, -20);
```

**Comment by tutyamxx** [comment]
thank you kindly, i appreciate it a lot!
